---
- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Install polybar
  become: true
  community.general.pacman:
    name: polybar
    state: present
