---
# https://github.com/polybar/polybar/wiki/Compiling
- name: Update Repository cache when Ubuntu
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - git
    - cmake
    - cmake-data
    - pkg-config
    - python3-sphinx
    - python3-packaging
    - libuv1-dev
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - libxcb-composite0-dev
    - python3-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev

- name: "Download polybar-{{ polybar.version }}.tar.gz"
  become: false
  get_url:
    url: "https://github.com/polybar/polybar/releases/download/{{ polybar.version }}/polybar-{{ polybar.version }}.tar.gz"
    dest: "/tmp/polybar-{{ polybar.version }}.tar.gz"

- name: "Extract polybar-{{ polybar.version }}.tar.gz"
  become: false
  unarchive:
    remote_src: true
    src: "/tmp/polybar-{{ polybar.version }}.tar.gz"
    dest: "/tmp/"

- name: Build polybar
  command: ./build.sh -f --auto
  become: false
  args:
    chdir: "/tmp/polybar-{{ polybar.version }}"
    creates: /usr/local/bin/polybar
